server:
  port: 8081

spring:
  application:
    name: user-service

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
  config: classpath:logback.xml

management:
  context-path: "/manage"
  metrics:
    enable:
      tomcat: true
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
  endpoints:
    enabled-by-default: true
    web:
      base-path: "/manage"
      exposure:
        include: "health,refresh,metrics"
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
