name: Build Java JAR

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the build on
  pull_request:
    branches:
      - main  # Adjust to the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean package

    - name: Upload JAR artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: user-service
        path: target/*.jar  # Assumes Maven output is in the target directory
